#!/bin/bash
# test_completions.sh — end-to-end checks for shai-completions generate + install (zsh + bash)
# Covers: shai-completions — usage errors, syntax validity, per-script coverage, flag aliases,
#         subcommand dispatch, dynamic candidates, install-dir resolution, determinism,
#         install targets/instructions/write failures, checked-in freshness of
#         completions/_shai and completions/shai.bash, and the check subcommand
#         (coverage, flag sync, freshness, _completions_ignore) on a hermetic fixture repo
set -uo pipefail
# shellcheck source=tests/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

echo "shai-completions"

GEN="$DIR/shai-completions"

# --- usage errors exit 2 ---------------------------------------------------
assert_exit 2 "no arguments is a usage error" -- "$GEN"
assert_exit 2 "unknown subcommand is a usage error" -- "$GEN" frobnicate
assert_exit 2 "missing shell argument is a usage error" -- "$GEN" generate
assert_exit 2 "unknown shell is a usage error" -- "$GEN" generate fish
assert_exit 2 "extra argument is a usage error" -- "$GEN" generate zsh extra

# --- generation failures exit 1 --------------------------------------------
# The generator resolves completions.json next to the script itself, so failure
# fixtures need their own copy of shai-completions.
BADGEN="$(mktemp -d)"
_CLEANUP_DIRS+=("$BADGEN")
cp "$GEN" "$BADGEN/shai-completions"
chmod +x "$BADGEN/shai-completions"

# Path 1: a manifest that fails the jq -e shape guard.
printf 'not a manifest\n' >"$BADGEN/completions.json"
assert_exit 1 "invalid manifest is a generation failure (zsh)" -- "$BADGEN/shai-completions" generate zsh
assert_exit 1 "invalid manifest is a generation failure (bash)" -- "$BADGEN/shai-completions" generate bash

# Path 2: a referenced type with no command, builtin, or hint — the zsh
# generator's type_action errors; docs.sh does not reject this shape.
cat >"$BADGEN/completions.json" <<'EOF'
{"scripts":{"shai-eval":{"flags":{},"positional":[{"name":"x","type":"ghost"}]}},"types":{"ghost":{"description":"no completion source"}}}
EOF
assert_exit 1 "type with no command, builtin, or hint is a generation failure" -- "$BADGEN/shai-completions" generate zsh

# --- generation ------------------------------------------------------------
ZSH_OUT="$("$GEN" generate zsh)"
RC=$?
assert_eq "$RC" "0" "generate zsh exits 0"
BASH_OUT="$("$GEN" generate bash)"
RC=$?
assert_eq "$RC" "0" "generate bash exits 0"

# Non-empty guards so the syntax checks below cannot pass vacuously on empty output.
if [ -n "$ZSH_OUT" ]; then
  echo -e "  ${GREEN}✓${NC} generate zsh emits non-empty output"
else
  echo -e "  ${RED}✗${NC} generate zsh emits non-empty output"
  FAILED=1
fi
if [ -n "$BASH_OUT" ]; then
  echo -e "  ${GREEN}✓${NC} generate bash emits non-empty output"
else
  echo -e "  ${RED}✗${NC} generate bash emits non-empty output"
  FAILED=1
fi

# Determinism: the same manifest must produce byte-identical output (no timestamps).
ZSH_OUT2="$("$GEN" generate zsh)"
assert_eq "$ZSH_OUT2" "$ZSH_OUT" "generate zsh is deterministic"
BASH_OUT2="$("$GEN" generate bash)"
assert_eq "$BASH_OUT2" "$BASH_OUT" "generate bash is deterministic"

# Checked-in files are fully generated: they must match `generate` output byte for byte.
# A compact diff (not the full bodies) is printed on mismatch so drift is debuggable.
if [ "$ZSH_OUT" = "$(cat "$DIR/completions/_shai")" ]; then
  echo -e "  ${GREEN}✓${NC} completions/_shai matches generate zsh"
else
  echo -e "  ${RED}✗${NC} completions/_shai differs from generate zsh"
  diff -u "$DIR/completions/_shai" <(printf '%s\n' "$ZSH_OUT") | head -n 40 || true
  FAILED=1
fi
if [ "$BASH_OUT" = "$(cat "$DIR/completions/shai.bash")" ]; then
  echo -e "  ${GREEN}✓${NC} completions/shai.bash matches generate bash"
else
  echo -e "  ${RED}✗${NC} completions/shai.bash differs from generate bash"
  diff -u "$DIR/completions/shai.bash" <(printf '%s\n' "$BASH_OUT") | head -n 40 || true
  FAILED=1
fi

# Every script in the manifest gets a completion function in both outputs.
while IFS= read -r name; do
  assert_contains "$ZSH_OUT" "_${name}() {" "zsh: $name gets a completion function"
  assert_contains "$BASH_OUT" "complete -F _${name//-/_} $name" "bash: $name gets a completion function"
done < <(jq -r '.scripts | keys[]' "$DIR/completions.json")

# Header marker on both generated files.
assert_contains "$ZSH_OUT" "# Generated by shai-completions generate — do not edit manually" \
  "zsh output carries the generated-file header"
assert_contains "$BASH_OUT" "# Generated by shai-completions generate — do not edit manually" \
  "bash output carries the generated-file header"

# --- install ---------------------------------------------------------------
assert_exit 2 "install without a shell is a usage error" -- "$GEN" install
assert_exit 2 "install with an unknown shell is a usage error" -- "$GEN" install fish
assert_exit 2 "install with an extra argument is a usage error" -- "$GEN" install zsh extra

INSTALL_XDG="$(mktemp -d)"
_CLEANUP_DIRS+=("$INSTALL_XDG")

OUT="$(XDG_DATA_HOME="$INSTALL_XDG" "$GEN" install zsh)"
RC=$?
assert_eq "$RC" "0" "install zsh exits 0"
assert_eq "$([ -f "$INSTALL_XDG/zsh/site-functions/_shai" ] && echo y)" "y" \
  "install zsh creates the site-functions directory and file"
assert_eq "$(cat "$INSTALL_XDG/zsh/site-functions/_shai")" "$ZSH_OUT" \
  "install zsh writes byte-identical generate zsh output"
assert_contains "$OUT" "Installed zsh completions to $INSTALL_XDG/zsh/site-functions/_shai" \
  "install zsh prints the success line with the path written"
assert_contains "$OUT" \
  "Add to .zshrc: fpath=($INSTALL_XDG/zsh/site-functions \$fpath); autoload -Uz compinit && compinit" \
  "install zsh prints the setup instruction with the resolved site-functions directory"
if [[ "$OUT" == *"~/.local/share"* ]]; then
  echo -e "  ${RED}✗${NC} install zsh instruction names the resolved dir, not a ~/.local/share literal"
  FAILED=1
else
  echo -e "  ${GREEN}✓${NC} install zsh instruction names the resolved dir, not a ~/.local/share literal"
fi

OUT="$(XDG_DATA_HOME="$INSTALL_XDG" "$GEN" install bash)"
RC=$?
assert_eq "$RC" "0" "install bash exits 0"
assert_eq "$([ -f "$INSTALL_XDG/bash-completion/completions/shai" ] && echo y)" "y" \
  "install bash creates the bash-completion directory and file"
assert_eq "$(cat "$INSTALL_XDG/bash-completion/completions/shai")" "$BASH_OUT" \
  "install bash writes byte-identical generate bash output"
assert_contains "$OUT" "Installed bash completions to $INSTALL_XDG/bash-completion/completions/shai" \
  "install bash prints the success line with the path written"
assert_contains "$OUT" \
  "Add to .bashrc: [[ -r $INSTALL_XDG/bash-completion/completions/shai ]] && source $INSTALL_XDG/bash-completion/completions/shai" \
  "install bash prints the setup instruction with the resolved completion path"

# Reinstall into the existing directory: the file is overwritten, and no setup instruction
# repeats. Positive control: the same install printed the instruction above when the
# directory was newly created, so this absence assertion cannot pass vacuously.
OUT="$(XDG_DATA_HOME="$INSTALL_XDG" "$GEN" install zsh)"
assert_contains "$OUT" "Installed zsh completions to" \
  "reinstall still prints the success line"
if [[ "$OUT" == *"Add to .zshrc"* ]]; then
  echo -e "  ${RED}✗${NC} reinstall prints no setup instruction (directory already exists)"
  FAILED=1
else
  echo -e "  ${GREEN}✓${NC} reinstall prints no setup instruction (directory already exists)"
fi

# Write failure: a regular file where the target directory should live blocks mkdir -p,
# so install exits 1 with an error line instead of clobbering anything.
BLOCKED="$(mktemp -d)"
_CLEANUP_DIRS+=("$BLOCKED")
printf 'x\n' >"$BLOCKED/zsh"
OUT="$(XDG_DATA_HOME="$BLOCKED" "$GEN" install zsh 2>&1)" && RC=0 || RC=$?
assert_eq "$RC" "1" "install zsh exits 1 when the target directory cannot be created"
assert_contains "$OUT" "error:" "install zsh names the write failure"

# Atomic write: a generation failure must leave an existing completion file intact
# (temp file + mv), and no temp file may linger next to it.
ATOM="$(mktemp -d)"
_CLEANUP_DIRS+=("$ATOM")
mkdir -p "$ATOM/zsh/site-functions"
printf 'pre-existing\n' >"$ATOM/zsh/site-functions/_shai"
cp "$GEN" "$ATOM/shai-completions"
chmod +x "$ATOM/shai-completions"
printf 'not a manifest\n' >"$ATOM/completions.json"
OUT="$(XDG_DATA_HOME="$ATOM" "$ATOM/shai-completions" install zsh 2>&1)" && RC=0 || RC=$?
assert_eq "$RC" "1" "install zsh exits 1 when generation fails"
assert_eq "$(cat "$ATOM/zsh/site-functions/_shai")" "pre-existing" \
  "install zsh preserves an existing completion file when generation fails"
assert_contains "$OUT" "error:" "install zsh names the generation failure"
assert_eq "$(ls -A "$ATOM/zsh/site-functions")" "_shai" \
  "install zsh leaves no temp file behind when generation fails"

# --- check: usage + the real repo ------------------------------------------
assert_exit 2 "check with an extra argument is a usage error" -- "$GEN" check bogus

# The real repo is the acceptance criterion: coverage (every git-tracked shai-*
# script has a manifest entry), flag sync (every parsed --flag is declared), and
# freshness (the checked-in files match generate output) all hold at once.
out="$("$GEN" check 2>&1)"
assert_eq "$?" "0" "check: the real repo passes coverage, flag sync, and freshness"

# --- check: coverage, flag sync, freshness on a hermetic fixture repo ------
# check derives its script list from git and its manifest + generated files from
# the script's own directory, so the fixture is a scratch git repo with its own
# copy of shai-completions, its own completions.json, and generated completions/.
FX="$(mktemp -d)"
_CLEANUP_DIRS+=("$FX")
git -C "$FX" init -q
cp "$GEN" "$FX/shai-completions"
chmod +x "$FX/shai-completions"
cat >"$FX/completions.json" <<'EOF'
{
  "scripts": {
    "shai-alpha": {
      "description": "fixture script with declared flags",
      "flags": {
        "--alpha": { "description": "declared alpha flag" }
      }
    },
    "shai-completions": { "description": "fixture copy of the generator", "flags": {} },
    "shai-orphan": { "description": "manifest entry with no script behind it", "flags": {} }
  },
  "types": {}
}
EOF
cat >"$FX/shai-alpha" <<'EOF'
#!/bin/bash
# shai-alpha — fixture script for shai-completions check
set -euo pipefail
case "$1" in
  --alpha) ALPHA=true ;;
esac
EOF
git -C "$FX" add shai-alpha shai-completions
mkdir -p "$FX/completions"
"$FX/shai-completions" generate zsh >"$FX/completions/_shai"
"$FX/shai-completions" generate bash >"$FX/completions/shai.bash"

# Baseline: everything in sync passes. This is also the positive control for the
# coverage cases: a script with an entry passes, and shai-orphan (a manifest entry
# with no script behind it) is not a failure.
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "0" "check: an in-sync fixture passes (manifest-only entry tolerated)"

# Coverage mutation: a tracked shai-* script with no manifest entry fails and is
# named. (Mutation-checked: the failure comes from the coverage loop — break that
# loop and this assertion goes red.)
cat >"$FX/shai-gamma" <<'EOF'
#!/bin/bash
# shai-gamma — tracked fixture script with no manifest entry
set -euo pipefail
EOF
git -C "$FX" add shai-gamma
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "1" "check: a tracked script with no manifest entry fails"
assert_contains "$out" "error: shai-gamma has no completions.json entry" \
  "check: coverage failure names the missing script"

# Restore: removing the untracked-in-manifest script makes the check pass again.
git -C "$FX" rm -q --cached shai-gamma
rm -f "$FX/shai-gamma"
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "0" "check: coverage failure disappears once the script is gone"

# Flag sync mutation: a --flag) case arm the manifest does not declare fails and
# names both script and flag. (Mutation-checked: break the declared_flag lookup
# and this assertion goes red.)
cat >"$FX/shai-alpha" <<'EOF'
#!/bin/bash
# shai-alpha — fixture script for shai-completions check
set -euo pipefail
case "$1" in
  --alpha) ALPHA=true ;;
  --beta) BETA=true ;;
esac
EOF
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "1" "check: a script flag missing from the manifest fails"
assert_contains "$out" "error: shai-alpha parses --beta" \
  "check: flag sync names the script and the undeclared flag"

# Declaring the flag (and regenerating, which the manifest change now requires)
# makes the check pass again.
jq '.scripts["shai-alpha"].flags["--beta"] = {"description": "declared beta flag"}' \
  "$FX/completions.json" >"$FX/completions.json.tmp"
mv "$FX/completions.json.tmp" "$FX/completions.json"
"$FX/shai-completions" generate zsh >"$FX/completions/_shai"
"$FX/shai-completions" generate bash >"$FX/completions/shai.bash"
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "0" "check: flags declared in both places pass"

# False-positive suppression: --gamma is a forwarded option (the same shape as
# PRINT_OPTS=(--dispatches)), not parsed by the fixture script, so the arm-shaped
# regex catches it. Without the _completions_ignore comment it fails...
cat >"$FX/shai-alpha" <<'EOF'
#!/bin/bash
# shai-alpha — fixture script for shai-completions check
set -euo pipefail
case "$1" in
  --alpha) ALPHA=true ;;
  --beta) BETA=true ;;
esac
GAMMA_OPTS=(--gamma)
EOF
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "1" "check: a --flag) false positive without an ignore comment fails"
assert_contains "$out" "parses --gamma" "check: names the false-positive flag"

# ...and the `# _completions_ignore: --gamma` comment silences it.
cat >"$FX/shai-alpha" <<'EOF'
#!/bin/bash
# shai-alpha — fixture script for shai-completions check
set -euo pipefail
case "$1" in
  --alpha) ALPHA=true ;;
  --beta) BETA=true ;;
esac
# _completions_ignore: --gamma (forwarded to a helper, not parsed here)
GAMMA_OPTS=(--gamma)
EOF
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "0" "check: _completions_ignore suppresses the false positive"

# ...and an indented one does too (mutation-checked: restoring the ^# anchor makes
# this assertion go red, since the indented comment no longer suppresses).
cat >"$FX/shai-alpha" <<'EOF'
#!/bin/bash
# shai-alpha — fixture script for shai-completions check
set -euo pipefail
case "$1" in
  --alpha) ALPHA=true ;;
  --beta) BETA=true ;;
esac
if [ -n "${GAMMA_OPTS:-}" ]; then
  # _completions_ignore: --gamma (forwarded to a helper, not parsed here)
  GAMMA_OPTS=(--gamma)
fi
EOF
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "0" "check: an indented _completions_ignore comment also suppresses"

# Freshness mutation: a manifest change without regeneration fails, shows the
# stale-file diff (including the new manifest flag), and names the stale file.
jq '.scripts["shai-alpha"].flags["--delta"] = {"description": "declared delta flag"}' \
  "$FX/completions.json" >"$FX/completions.json.tmp"
mv "$FX/completions.json.tmp" "$FX/completions.json"
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "1" "check: a manifest change without regeneration fails"
assert_contains "$out" "error: completions/_shai is stale" "check: freshness names the stale file"
assert_contains "$out" "error: completions/shai.bash is stale" "check: freshness names both stale files"
assert_contains "$out" "--delta" "check: the freshness diff shows the new manifest flag"

# Regenerating restores green.
"$FX/shai-completions" generate zsh >"$FX/completions/_shai"
"$FX/shai-completions" generate bash >"$FX/completions/shai.bash"
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "0" "check: up-to-date generated files pass"

# Byte-identity: a checked-in file missing its final newline must fail the gate.
# (Mutation-checked: comparing via command substitution instead of cmp strips
# trailing newlines on both sides and lets this pass — restore it and this goes red.)
"$FX/shai-completions" generate zsh >"$FX/completions/_shai.tmp"
printf '%s' "$(cat "$FX/completions/_shai.tmp")" >"$FX/completions/_shai"
rm -f "$FX/completions/_shai.tmp"
out="$("$FX/shai-completions" check 2>&1)"
assert_eq "$?" "1" "check: a checked-in file missing its final newline fails"
assert_contains "$out" "error: completions/_shai is stale" \
  "check: byte-compare names the newline-stripped file"

# --- bash syntax + execution -----------------------------------------------
if printf '%s\n' "$BASH_OUT" | bash -n; then
  echo -e "  ${GREEN}✓${NC} bash -n accepts generated bash output"
else
  echo -e "  ${RED}✗${NC} bash -n rejects generated bash output"
  FAILED=1
fi

# Drive the checked-in bash file with a hand-built COMP_WORDS/COMP_CWORD
# context: bash completion functions are plain functions, so they are fully
# exercisable offline. $BASH_BIN is captured before any PATH override so the
# harness shell itself is not subject to the stub PATHs the cases need.
BASH_BIN="$(command -v bash)"
run_bash() {
  # $1: function to call, $2..: COMP_WORDS (COMP_CWORD = ${#COMP_WORDS[@]} - 1)
  local fn="$1"
  shift
  "$BASH_BIN" -c '
    source "$1/completions/shai.bash"
    shift
    COMP_WORDS=("$@")
    COMP_CWORD=$(( ${#COMP_WORDS[@]} - 1 ))
    '"$fn"'
    printf "%s\n" "${COMPREPLY[*]}"
  ' _ "$DIR" "$@"
}

out="$(run_bash _shai_runs shai-runs --)"
assert_contains "$out" "--session" "bash: shai-runs --<TAB> offers --session"
assert_contains "$out" "--recent" "bash: shai-runs --<TAB> offers --recent"
assert_contains "$out" "--failed" "bash: shai-runs --<TAB> offers --failed"
assert_contains "$out" "--after" "bash: shai-runs --<TAB> offers --after"
assert_contains "$out" "--before" "bash: shai-runs --<TAB> offers --before"
assert_contains "$out" "--json" "bash: shai-runs --<TAB> offers --json"

out="$(run_bash _shai_repl shai-repl -)"
assert_contains "$out" "-q" "bash: shai-repl -<TAB> offers -q"
assert_contains "$out" "--quiet" "bash: shai-repl -<TAB> offers --quiet"

out="$(run_bash _shai_workflow shai-workflow "")"
assert_contains "$out" "list" "bash: shai-workflow <TAB> offers list"
assert_contains "$out" "run" "bash: shai-workflow <TAB> offers run"
assert_contains "$out" "describe" "bash: shai-workflow <TAB> offers describe"

out="$(run_bash _shai_completions shai-completions "")"
assert_contains "$out" "generate" "bash: shai-completions <TAB> offers generate"
assert_contains "$out" "install" "bash: shai-completions <TAB> offers install"

out="$(run_bash _shai_completions shai-completions install "")"
assert_contains "$out" "zsh" "bash: shai-completions install <TAB> offers zsh"
assert_contains "$out" "bash" "bash: shai-completions install <TAB> offers bash"

# Dynamic candidates: run IDs and session IDs from $SHAI_HOME.
mkdir -p "$SHAI_HOME/runs/run_abc123" "$SHAI_HOME/runs/run_def456"
mkdir -p "$SHAI_HOME/sessions"
printf '' >"$SHAI_HOME/sessions/sess_one.jsonl"
printf '' >"$SHAI_HOME/sessions/sess_two.jsonl"

out="$(run_bash _shai_retry shai-retry --run run_a)"
assert_contains "$out" "run_abc123" "bash: shai-retry --run <TAB> lists run IDs from \$SHAI_HOME/runs"
if [[ "$out" != *run_def456* ]]; then
  echo -e "  ${GREEN}✓${NC} bash: --run completion is prefix-filtered (run_def456 not offered for 'run_a')"
else
  echo -e "  ${RED}✗${NC} bash: --run completion is prefix-filtered (got $out)"
  FAILED=1
fi

out="$(run_bash _shai_runs shai-runs --session sess_o)"
assert_contains "$out" "sess_one" "bash: shai-runs --session <TAB> lists session IDs from \$SHAI_HOME/sessions"
if [[ "$out" != *sess_two* ]]; then
  echo -e "  ${GREEN}✓${NC} bash: --session completion is prefix-filtered (sess_two not offered for 'sess_o')"
else
  echo -e "  ${RED}✗${NC} bash: --session completion is prefix-filtered (got $out)"
  FAILED=1
fi

# Install-directory resolution: install.sh writes a wrapper script
# `exec '<install-dir>/shai-repl' "$@"`, and the generated files extract the
# directory at load time. A fake install dir exercises that path end to end.
WF="$(mktemp -d)"
_CLEANUP_DIRS+=("$WF")
mkdir -p "$WF/workflows/heartbeat" "$WF/workflows/jira_worker" "$WF/prompts" "$WF/work flows"
cat >"$WF/workflows/heartbeat/run.sh" <<'EOF'
#!/bin/bash
# heartbeat/run.sh — pipeline liveness probe
# Usage: workflows/heartbeat/run.sh
# Reads: DEEPSEEK_API_KEY from environment
# Writes: timestamped pass/fail line to stderr
# Exit: 0 on pipeline success; 1 on pipeline failure
set -euo pipefail
EOF
cat >"$WF/workflows/jira_worker/run.sh" <<'EOF'
#!/bin/bash
# jira_worker/run.sh — file Jira tickets from issue text
# Usage: workflows/jira_worker/run.sh OWNER/REPO PROJ-123
# Reads: JIRA_API_TOKEN from environment
# Writes: a Jira ticket
# Exit: 0 on success; 1 on failure
set -euo pipefail
EOF
printf 'x\n' >"$WF/prompts/system.txt"

STUB_BIN="$(mktemp -d)"
_CLEANUP_DIRS+=("$STUB_BIN")
printf "#!/bin/bash\nexec '%s/shai-repl' \"\$@\"\n" "$WF" >"$STUB_BIN/shai-repl"
chmod +x "$STUB_BIN/shai-repl"

out="$(PATH="$STUB_BIN:$PATH" bash -c '
  source "$1/completions/shai.bash"
  printf "%s" "${_shai_dir:-UNSET}"
' _ "$DIR")"
assert_eq "$out" "$WF" "bash: _shai_dir resolves via the shai-repl wrapper script"

out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_workflow shai-workflow run "")"
assert_contains "$out" "heartbeat" "bash: shai-workflow run <TAB> completes workflow names"
assert_contains "$out" "jira_worker" "bash: shai-workflow run <TAB> completes every workflow name"

out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_failures shai-failures list --workflow hea)"
assert_contains "$out" "heartbeat" "bash: shai-failures list --workflow <TAB> completes workflow names"

# A flag value between the subcommand and the cursor must not hide the
# positional slot: track consumed positionals instead of the raw COMP_CWORD.
out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_supervise shai-supervise install --interval 15min "")"
assert_contains "$out" "heartbeat" \
  "bash: shai-supervise install --interval 15min <TAB> completes workflow names"
out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_supervise shai-supervise install --interval "")"
assert_eq "$out" "" "bash: shai-supervise install --interval <TAB> completes nothing at the flag value"

out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_prompt shai-prompt sy)"
assert_contains "$out" "system" "bash: shai-prompt <TAB> completes prompt names"

out="$(PATH="$STUB_BIN:$PATH" bash -c '
  source "$1/completions/shai.bash"
  cd "$2" || exit
  COMP_WORDS=(shai-tools workf)
  COMP_CWORD=1
  _shai_tools
  printf "%s\n" "${COMPREPLY[*]}"
' _ "$DIR" "$WF")"
assert_contains "$out" "workflows" "bash: shai-tools <TAB> completes filesystem paths (file type)"

# Paths containing spaces must arrive as single COMPREPLY entries (newline-only
# word splitting + compopt -o filenames for readline), not fragmented words.
out="$(PATH="$STUB_BIN:$PATH" bash -c '
  source "$1/completions/shai.bash"
  cd "$2" || exit
  COMP_WORDS=(shai-tools "work f")
  COMP_CWORD=1
  _shai_tools
  printf "%s\n" "${#COMPREPLY[@]}:${COMPREPLY[*]}"
' _ "$DIR" "$WF")"
assert_contains "$out" "1:" "bash: shai-tools completes a space-containing path as one candidate"
assert_contains "$out" "work flows" "bash: the spaced candidate keeps its full name"

# The readlink fallback: a real (non-wrapper) shai-repl script on $PATH resolves
# to its own directory.
printf '#!/bin/bash\n# shai-repl — Interactive REPL\necho repl\n' >"$WF/shai-repl"
chmod +x "$WF/shai-repl"
out="$(PATH="$WF:$PATH" bash -c '
  source "$1/completions/shai.bash"
  printf "%s" "${_shai_dir:-UNSET}"
' _ "$DIR")"
assert_eq "$out" "$WF" "bash: _shai_dir resolves a real shai-repl script via readlink"

# Negative control for the resolution paths above: with no shai-repl on $PATH,
# install-dir candidates return nothing instead of erroring or globbing garbage.
NOSTUB="$(mktemp -d)"
_CLEANUP_DIRS+=("$NOSTUB")
out="$(PATH="$NOSTUB" run_bash _shai_workflow shai-workflow run "")"
assert_eq "$out" "" "bash: no shai-repl on PATH means no workflow candidates"

# --- zsh syntax + runtime --------------------------------------------------
if command -v zsh &>/dev/null; then
  if printf '%s\n' "$ZSH_OUT" | zsh -n 2>/dev/null; then
    echo -e "  ${GREEN}✓${NC} zsh -n accepts generated zsh output"
  else
    echo -e "  ${RED}✗${NC} zsh -n rejects generated zsh output"
    FAILED=1
  fi

  # The install-dir resolution block is shared logic — verify it in a real zsh
  # (compdef errors on direct sourcing are expected without compinit; suppressed).
  out="$(PATH="$STUB_BIN:$PATH" zsh -f -c \
    'source "$1/completions/_shai" 2>/dev/null; print -r -- "${_shai_dir:-UNSET}"' _ "$DIR")"
  assert_eq "$out" "$WF" "zsh: _shai_dir resolves via the shai-repl wrapper script"

  # Drive an interactive zsh through a pseudo-terminal and complete for real:
  # zpty gives the spawned zsh a TTY, so TAB runs the compsys end to end. The
  # listing must contain the workflow name and its purpose line (the zsh
  # description), plus the flag set for shai-runs.
  ZTMP="$(mktemp -d)"
  _CLEANUP_DIRS+=("$ZTMP")
  cat >"$ZTMP/harness.zsh" <<EOF
zmodload zsh/zpty || exit 77
zpty shai_comp 'env TERM=dumb zsh -f' || exit 77
zpty -w shai_comp \$'autoload -Uz compinit && compinit -u && source "$DIR/completions/_shai"\n'
zpty -w shai_comp \$'shai-workflow run \t'
zpty -w shai_comp \$'\cc'
zpty -w shai_comp \$'shai-runs --\t'
zpty -w shai_comp \$'\cc'
zpty -w shai_comp \$'shai-repl -\t'
zpty -w shai_comp \$'\cc'
zpty -w shai_comp \$'exit\n'
local out="" line tries=0
while [ "\$tries" -lt 10 ]; do
  if zpty -t shai_comp; then
    if zpty -r shai_comp line; then
      out+="\$line"
      tries=0
    else
      break
    fi
  else
    sleep 1
    tries=\$((tries + 1))
  fi
done
print -r -- "\$out"
EOF
  ZOUT="$(PATH="$STUB_BIN:$PATH" zsh -f "$ZTMP/harness.zsh" 2>/dev/null)"
  if [ "$?" -eq 77 ]; then
    echo -e "  ${GREEN}✓${NC} zsh pty harness skipped (zpty unavailable)"
  else
    assert_contains "$ZOUT" "heartbeat" "zsh: shai-workflow run <TAB> completes workflow names"
    assert_contains "$ZOUT" "pipeline liveness probe" \
      "zsh: shai-workflow run <TAB> shows the workflow purpose as description"
    assert_contains "$ZOUT" "--session" "zsh: shai-runs --<TAB> offers --session"
    assert_contains "$ZOUT" "--quiet" "zsh: shai-repl -<TAB> offers the --quiet alias"
  fi
else
  echo "  zsh not found — skipping zsh syntax and runtime checks"
fi

finish
