#!/bin/bash
# test_completions.sh — end-to-end checks for shai-completions generate (zsh + bash outputs)
# Covers: shai-completions — usage errors, syntax validity, per-script coverage, flag aliases,
#         subcommand dispatch, dynamic candidates, install-dir resolution, determinism,
#         checked-in freshness of completions/_shai and completions/shai.bash
set -uo pipefail
# shellcheck source=tests/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

echo "shai-completions"

GEN="$DIR/shai-completions"

# --- usage errors exit 2 ---------------------------------------------------
assert_exit 2 "no arguments is a usage error" -- "$GEN"
assert_exit 2 "unknown subcommand is a usage error" -- "$GEN" frobnicate
assert_exit 2 "missing shell argument is a usage error" -- "$GEN" generate
assert_exit 2 "unknown shell is a usage error" -- "$GEN" generate fish
assert_exit 2 "extra argument is a usage error" -- "$GEN" generate zsh extra

# --- generation ------------------------------------------------------------
ZSH_OUT="$("$GEN" generate zsh)"
RC=$?
assert_eq "$RC" "0" "generate zsh exits 0"
BASH_OUT="$("$GEN" generate bash)"
RC=$?
assert_eq "$RC" "0" "generate bash exits 0"

# Non-empty guards so the syntax checks below cannot pass vacuously on empty output.
if [ -n "$ZSH_OUT" ]; then
  echo -e "  ${GREEN}✓${NC} generate zsh emits non-empty output"
else
  echo -e "  ${RED}✗${NC} generate zsh emits non-empty output"
  FAILED=1
fi
if [ -n "$BASH_OUT" ]; then
  echo -e "  ${GREEN}✓${NC} generate bash emits non-empty output"
else
  echo -e "  ${RED}✗${NC} generate bash emits non-empty output"
  FAILED=1
fi

# Determinism: the same manifest must produce byte-identical output (no timestamps).
ZSH_OUT2="$("$GEN" generate zsh)"
assert_eq "$ZSH_OUT2" "$ZSH_OUT" "generate zsh is deterministic"
BASH_OUT2="$("$GEN" generate bash)"
assert_eq "$BASH_OUT2" "$BASH_OUT" "generate bash is deterministic"

# Checked-in files are fully generated: they must match `generate` output byte for byte.
# A compact diff (not the full bodies) is printed on mismatch so drift is debuggable.
if [ "$ZSH_OUT" = "$(cat "$DIR/completions/_shai")" ]; then
  echo -e "  ${GREEN}✓${NC} completions/_shai matches generate zsh"
else
  echo -e "  ${RED}✗${NC} completions/_shai differs from generate zsh"
  diff -u "$DIR/completions/_shai" <(printf '%s\n' "$ZSH_OUT") | head -n 40 || true
  FAILED=1
fi
if [ "$BASH_OUT" = "$(cat "$DIR/completions/shai.bash")" ]; then
  echo -e "  ${GREEN}✓${NC} completions/shai.bash matches generate bash"
else
  echo -e "  ${RED}✗${NC} completions/shai.bash differs from generate bash"
  diff -u "$DIR/completions/shai.bash" <(printf '%s\n' "$BASH_OUT") | head -n 40 || true
  FAILED=1
fi

# Every script in the manifest gets a completion function in both outputs.
while IFS= read -r name; do
  assert_contains "$ZSH_OUT" "_${name}() {" "zsh: $name gets a completion function"
  assert_contains "$BASH_OUT" "complete -F _${name//-/_} $name" "bash: $name gets a completion function"
done < <(jq -r '.scripts | keys[]' "$DIR/completions.json")

# Header marker on both generated files.
assert_contains "$ZSH_OUT" "# Generated by shai-completions generate — do not edit manually" \
  "zsh output carries the generated-file header"
assert_contains "$BASH_OUT" "# Generated by shai-completions generate — do not edit manually" \
  "bash output carries the generated-file header"

# --- bash syntax + execution -----------------------------------------------
if printf '%s\n' "$BASH_OUT" | bash -n; then
  echo -e "  ${GREEN}✓${NC} bash -n accepts generated bash output"
else
  echo -e "  ${RED}✗${NC} bash -n rejects generated bash output"
  FAILED=1
fi

# Drive the checked-in bash file with a hand-built COMP_WORDS/COMP_CWORD
# context: bash completion functions are plain functions, so they are fully
# exercisable offline. $BASH_BIN is captured before any PATH override so the
# harness shell itself is not subject to the stub PATHs the cases need.
BASH_BIN="$(command -v bash)"
run_bash() {
  # $1: function to call, $2..: COMP_WORDS (COMP_CWORD = ${#COMP_WORDS[@]} - 1)
  local fn="$1"
  shift
  "$BASH_BIN" -c '
    source "$1/completions/shai.bash"
    shift
    COMP_WORDS=("$@")
    COMP_CWORD=$(( ${#COMP_WORDS[@]} - 1 ))
    '"$fn"'
    printf "%s\n" "${COMPREPLY[*]}"
  ' _ "$DIR" "$@"
}

out="$(run_bash _shai_runs shai-runs --)"
assert_contains "$out" "--session" "bash: shai-runs --<TAB> offers --session"
assert_contains "$out" "--recent" "bash: shai-runs --<TAB> offers --recent"
assert_contains "$out" "--failed" "bash: shai-runs --<TAB> offers --failed"
assert_contains "$out" "--after" "bash: shai-runs --<TAB> offers --after"
assert_contains "$out" "--before" "bash: shai-runs --<TAB> offers --before"
assert_contains "$out" "--json" "bash: shai-runs --<TAB> offers --json"

out="$(run_bash _shai_repl shai-repl -)"
assert_contains "$out" "-q" "bash: shai-repl -<TAB> offers -q"
assert_contains "$out" "--quiet" "bash: shai-repl -<TAB> offers --quiet"

out="$(run_bash _shai_workflow shai-workflow "")"
assert_contains "$out" "list" "bash: shai-workflow <TAB> offers list"
assert_contains "$out" "run" "bash: shai-workflow <TAB> offers run"
assert_contains "$out" "describe" "bash: shai-workflow <TAB> offers describe"

# Dynamic candidates: run IDs and session IDs from $SHAI_HOME.
mkdir -p "$SHAI_HOME/runs/run_abc123" "$SHAI_HOME/runs/run_def456"
mkdir -p "$SHAI_HOME/sessions"
printf '' >"$SHAI_HOME/sessions/sess_one.jsonl"
printf '' >"$SHAI_HOME/sessions/sess_two.jsonl"

out="$(run_bash _shai_retry shai-retry --run run_a)"
assert_contains "$out" "run_abc123" "bash: shai-retry --run <TAB> lists run IDs from \$SHAI_HOME/runs"
if [[ "$out" != *run_def456* ]]; then
  echo -e "  ${GREEN}✓${NC} bash: --run completion is prefix-filtered (run_def456 not offered for 'run_a')"
else
  echo -e "  ${RED}✗${NC} bash: --run completion is prefix-filtered (got $out)"
  FAILED=1
fi

out="$(run_bash _shai_runs shai-runs --session sess_o)"
assert_contains "$out" "sess_one" "bash: shai-runs --session <TAB> lists session IDs from \$SHAI_HOME/sessions"
if [[ "$out" != *sess_two* ]]; then
  echo -e "  ${GREEN}✓${NC} bash: --session completion is prefix-filtered (sess_two not offered for 'sess_o')"
else
  echo -e "  ${RED}✗${NC} bash: --session completion is prefix-filtered (got $out)"
  FAILED=1
fi

# Install-directory resolution: install.sh writes a wrapper script
# `exec '<install-dir>/shai-repl' "$@"`, and the generated files extract the
# directory at load time. A fake install dir exercises that path end to end.
WF="$(mktemp -d)"
_CLEANUP_DIRS+=("$WF")
mkdir -p "$WF/workflows/heartbeat" "$WF/workflows/jira_worker" "$WF/prompts"
cat >"$WF/workflows/heartbeat/run.sh" <<'EOF'
#!/bin/bash
# heartbeat/run.sh — pipeline liveness probe
# Usage: workflows/heartbeat/run.sh
# Reads: DEEPSEEK_API_KEY from environment
# Writes: timestamped pass/fail line to stderr
# Exit: 0 on pipeline success; 1 on pipeline failure
set -euo pipefail
EOF
cat >"$WF/workflows/jira_worker/run.sh" <<'EOF'
#!/bin/bash
# jira_worker/run.sh — file Jira tickets from issue text
# Usage: workflows/jira_worker/run.sh OWNER/REPO PROJ-123
# Reads: JIRA_API_TOKEN from environment
# Writes: a Jira ticket
# Exit: 0 on success; 1 on failure
set -euo pipefail
EOF
printf 'x\n' >"$WF/prompts/system.txt"

STUB_BIN="$(mktemp -d)"
_CLEANUP_DIRS+=("$STUB_BIN")
printf "#!/bin/bash\nexec '%s/shai-repl' \"\$@\"\n" "$WF" >"$STUB_BIN/shai-repl"
chmod +x "$STUB_BIN/shai-repl"

out="$(PATH="$STUB_BIN:$PATH" bash -c '
  source "$1/completions/shai.bash"
  printf "%s" "${_shai_dir:-UNSET}"
' _ "$DIR")"
assert_eq "$out" "$WF" "bash: _shai_dir resolves via the shai-repl wrapper script"

out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_workflow shai-workflow run "")"
assert_contains "$out" "heartbeat" "bash: shai-workflow run <TAB> completes workflow names"
assert_contains "$out" "jira_worker" "bash: shai-workflow run <TAB> completes every workflow name"

out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_failures shai-failures list --workflow hea)"
assert_contains "$out" "heartbeat" "bash: shai-failures list --workflow <TAB> completes workflow names"

out="$(PATH="$STUB_BIN:$PATH" run_bash _shai_prompt shai-prompt sy)"
assert_contains "$out" "system" "bash: shai-prompt <TAB> completes prompt names"

out="$(PATH="$STUB_BIN:$PATH" bash -c '
  source "$1/completions/shai.bash"
  cd "$2" || exit
  COMP_WORDS=(shai-tools workf)
  COMP_CWORD=1
  _shai_tools
  printf "%s\n" "${COMPREPLY[*]}"
' _ "$DIR" "$WF")"
assert_contains "$out" "workflows" "bash: shai-tools <TAB> completes filesystem paths (file type)"

# The readlink fallback: a real (non-wrapper) shai-repl script on $PATH resolves
# to its own directory.
printf '#!/bin/bash\n# shai-repl — Interactive REPL\necho repl\n' >"$WF/shai-repl"
chmod +x "$WF/shai-repl"
out="$(PATH="$WF:$PATH" bash -c '
  source "$1/completions/shai.bash"
  printf "%s" "${_shai_dir:-UNSET}"
' _ "$DIR")"
assert_eq "$out" "$WF" "bash: _shai_dir resolves a real shai-repl script via readlink"

# Negative control for the resolution paths above: with no shai-repl on $PATH,
# install-dir candidates return nothing instead of erroring or globbing garbage.
NOSTUB="$(mktemp -d)"
_CLEANUP_DIRS+=("$NOSTUB")
out="$(PATH="$NOSTUB" run_bash _shai_workflow shai-workflow run "")"
assert_eq "$out" "" "bash: no shai-repl on PATH means no workflow candidates"

# --- zsh syntax + runtime --------------------------------------------------
if command -v zsh &>/dev/null; then
  if printf '%s\n' "$ZSH_OUT" | zsh -n 2>/dev/null; then
    echo -e "  ${GREEN}✓${NC} zsh -n accepts generated zsh output"
  else
    echo -e "  ${RED}✗${NC} zsh -n rejects generated zsh output"
    FAILED=1
  fi

  # The install-dir resolution block is shared logic — verify it in a real zsh
  # (compdef errors on direct sourcing are expected without compinit; suppressed).
  out="$(PATH="$STUB_BIN:$PATH" zsh -f -c \
    'source "$1/completions/_shai" 2>/dev/null; print -r -- "${_shai_dir:-UNSET}"' _ "$DIR")"
  assert_eq "$out" "$WF" "zsh: _shai_dir resolves via the shai-repl wrapper script"

  # Drive an interactive zsh through a pseudo-terminal and complete for real:
  # zpty gives the spawned zsh a TTY, so TAB runs the compsys end to end. The
  # listing must contain the workflow name and its purpose line (the zsh
  # description), plus the flag set for shai-runs.
  ZTMP="$(mktemp -d)"
  _CLEANUP_DIRS+=("$ZTMP")
  cat >"$ZTMP/harness.zsh" <<EOF
zmodload zsh/zpty || exit 77
zpty shai_comp 'env TERM=dumb zsh -f' || exit 77
zpty -w shai_comp \$'autoload -Uz compinit && compinit -u && source "$DIR/completions/_shai"\n'
zpty -w shai_comp \$'shai-workflow run \t'
zpty -w shai_comp \$'\cc'
zpty -w shai_comp \$'shai-runs --\t'
zpty -w shai_comp \$'\cc'
zpty -w shai_comp \$'shai-repl -\t'
zpty -w shai_comp \$'\cc'
zpty -w shai_comp \$'exit\n'
local out="" line tries=0
while [ "\$tries" -lt 10 ]; do
  if zpty -t shai_comp; then
    if zpty -r shai_comp line; then
      out+="\$line"
      tries=0
    else
      break
    fi
  else
    sleep 1
    tries=\$((tries + 1))
  fi
done
print -r -- "\$out"
EOF
  ZOUT="$(PATH="$STUB_BIN:$PATH" zsh -f "$ZTMP/harness.zsh" 2>/dev/null)"
  if [ "$?" -eq 77 ]; then
    echo -e "  ${GREEN}✓${NC} zsh pty harness skipped (zpty unavailable)"
  else
    assert_contains "$ZOUT" "heartbeat" "zsh: shai-workflow run <TAB> completes workflow names"
    assert_contains "$ZOUT" "pipeline liveness probe" \
      "zsh: shai-workflow run <TAB> shows the workflow purpose as description"
    assert_contains "$ZOUT" "--session" "zsh: shai-runs --<TAB> offers --session"
    assert_contains "$ZOUT" "--quiet" "zsh: shai-repl -<TAB> offers the --quiet alias"
  fi
else
  echo "  zsh not found — skipping zsh syntax and runtime checks"
fi

finish
