# Generated by shai-completions generate — do not edit manually
# Sources: completions.json — candidates resolve dynamically at completion time.

# Resolve the shai install directory once at load time: install.sh wrappers exec
# '<install-dir>/shai-repl'; dev clones put the real script on $PATH. Falls back
# gracefully when shai-repl is not on $PATH (install-dir candidates return none).
_shai_bin="$(command -v shai-repl 2>/dev/null)" || _shai_bin=""
if [ -n "$_shai_bin" ] && [ -f "$_shai_bin" ]; then
  _shai_dir="$(sed -n '2s/^exec .\(.*\)\/shai-repl.*/\1/p' "$_shai_bin" 2>/dev/null)"
  if [ -z "$_shai_dir" ]; then
    _shai_dir="$(readlink -f "$_shai_bin" 2>/dev/null)" || _shai_dir="$_shai_bin"
    _shai_dir="$(cd "$(dirname "$_shai_dir")" 2>/dev/null && pwd)"
  fi
else
  _shai_dir=""
fi
unset _shai_bin

# Dynamic candidate helpers: one per completions.json type with a command.
_shai_bash_session_id() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(ls "${SHAI_HOME:-$HOME/.shai}/sessions/" 2>/dev/null | sed 's/\.jsonl$//' | cut -f1)" -- "$cur") )
}
_shai_bash_run_id() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(ls "${SHAI_HOME:-$HOME/.shai}/runs/" 2>/dev/null | cut -f1)" -- "$cur") )
}
_shai_bash_workflow_name() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [ -z "${_shai_dir:-}" ] || [ ! -d "${_shai_dir:-}" ]; then
    COMPREPLY=()
    return
  fi
  COMPREPLY=( $(compgen -W "$(for d in "${_shai_dir}/workflows/"*/run.sh; do [ -f "$d" ] || continue; d="${d%/run.sh}"; n="${d##*/}"; p="$(sed -n '2s/^# //p' "$d/run.sh" 2>/dev/null)"; p="${p##*— }"; printf '%s\t%s\n' "$n" "$p"; done 2>/dev/null | cut -f1)" -- "$cur") )
}
_shai_bash_prompt_name() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [ -z "${_shai_dir:-}" ] || [ ! -d "${_shai_dir:-}" ]; then
    COMPREPLY=()
    return
  fi
  COMPREPLY=( $(compgen -W "$(ls "${_shai_dir}/prompts/" 2>/dev/null | sed 's/\.txt$//' | cut -f1)" -- "$cur") )
}
_shai_bash_shell() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' zsh bash | cut -f1)" -- "$cur") )
}

_shai_read() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--system --external" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_read shai-read
_shai_context() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--max-bytes" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_context shai-context
_shai_eval() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--tools-file" ]]; then
    COMPREPLY=( $(compgen -f -- "$cur") )
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--tools-file --model --max-tokens --dry-run --health-check" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_eval shai-eval
_shai_dispatch() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_dispatch shai-dispatch
_shai_loop() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--tools-file" ]]; then
    COMPREPLY=( $(compgen -f -- "$cur") )
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--tools --tools-file --model --max-tokens --quiet -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_loop shai-loop
_shai_print() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--debug --dispatches" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_print shai-print
_shai_stamp() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_stamp shai-stamp
_shai_ask() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--quiet --no-tools --model --max-tokens --external -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_ask shai-ask
_shai_repl() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--quiet -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_repl shai-repl
_shai_retry() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--run" ]]; then
    _shai_bash_run_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--quiet --run -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_retry shai-retry
_shai_sessions() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--recent --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_sessions shai-sessions
_shai_runs() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--session" ]]; then
    _shai_bash_session_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--session --recent --failed --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_runs shai-runs
_shai_trace() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--request --response --verbose --json" -- "$cur") )
    return
  fi
  if [ "$COMP_CWORD" -eq 1 ]; then
    _shai_bash_run_id
    return
  fi
  COMPREPLY=()
}
complete -F _shai_trace shai-trace
_shai_stats() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--session" ]]; then
    _shai_bash_session_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--session --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_stats shai-stats
_shai_failures() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "list show summary" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    list)
      if [[ "$prev" == "--workflow" ]]; then
        _shai_bash_workflow_name
        return
      fi
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--workflow --category --after --before --recent --json" -- "$cur") )
        return
      fi
      COMPREPLY=()
      ;;
    show)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--json" -- "$cur") )
        return
      fi
      COMPREPLY=()
      ;;
    summary)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--after --before --json" -- "$cur") )
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_failures shai-failures
_shai_ledgers() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--workflow" ]]; then
    _shai_bash_workflow_name
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--workflow --recent --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_ledgers shai-ledgers
_shai_doctor() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_doctor shai-doctor
_shai_version() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_version shai-version
_shai_tools() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -f -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_tools shai-tools
_shai_prompt() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    _shai_bash_prompt_name
    return
  fi
  COMPREPLY=()
}
complete -F _shai_prompt shai-prompt
_shai_workflow() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "list run describe" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    list)
      COMPREPLY=()
      ;;
    run)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    describe)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_workflow shai-workflow
_shai_supervise() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "install uninstall start stop status logs" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    install)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--interval" -- "$cur") )
        return
      fi
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    uninstall)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    start)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    stop)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    status)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--json" -- "$cur") )
        return
      fi
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    logs)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_supervise shai-supervise
_shai_prune() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--sessions --runs --ledgers --failures --dry-run --before" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_prune shai-prune
_shai_completions() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "generate" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    generate)
      if [ "$COMP_CWORD" -eq 2 ]; then
        _shai_bash_shell
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_completions shai-completions
