# Generated by shai-completions generate — do not edit manually
# Sources: completions.json — candidates resolve dynamically at completion time.

# Resolve the shai install directory once at load time: install.sh wrappers exec
# '<install-dir>/shai-repl'; dev clones put the real script on $PATH. Falls back
# gracefully when shai-repl is not on $PATH (install-dir candidates return none).
_shai_bin="$(command -v shai-repl 2>/dev/null)" || _shai_bin=""
if [ -n "$_shai_bin" ] && [ -f "$_shai_bin" ]; then
  _shai_dir="$(sed -n '2s/^exec .\(.*\)\/shai-repl.*/\1/p' "$_shai_bin" 2>/dev/null)"
  if [ -z "$_shai_dir" ]; then
    _shai_dir="$(readlink -f "$_shai_bin" 2>/dev/null)" || _shai_dir="$_shai_bin"
    _shai_dir="$(cd "$(dirname "$_shai_dir")" 2>/dev/null && pwd)"
  fi
else
  _shai_dir=""
fi
unset _shai_bin

# Dynamic candidate helpers: one per completions.json type with a command.
_shai_bash_session_id() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(ls "${SHAI_HOME:-$HOME/.shai}/sessions/" 2>/dev/null | sed -n 's/\.jsonl$//p' | cut -f1)" -- "$cur") )
}
_shai_bash_run_id() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(ls "${SHAI_HOME:-$HOME/.shai}/runs/" 2>/dev/null | cut -f1)" -- "$cur") )
}
_shai_bash_workflow_name() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [ -z "${_shai_dir:-}" ] || [ ! -d "${_shai_dir:-}" ]; then
    COMPREPLY=()
    return
  fi
  COMPREPLY=( $(compgen -W "$(for d in "${_shai_dir}/workflows/"*/run.sh; do [ -f "$d" ] || continue; d="${d%/run.sh}"; n="${d##*/}"; p="$(sed -n '2s/^# //p' "$d/run.sh" 2>/dev/null)"; p="${p##*— }"; printf '%s\t%s\n' "$n" "$p"; done 2>/dev/null | cut -f1)" -- "$cur") )
}
_shai_bash_prompt_name() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [ -z "${_shai_dir:-}" ] || [ ! -d "${_shai_dir:-}" ]; then
    COMPREPLY=()
    return
  fi
  COMPREPLY=( $(compgen -W "$(ls "${_shai_dir}/prompts/" 2>/dev/null | sed 's/\.txt$//' | cut -f1)" -- "$cur") )
}
_shai_bash_shell() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' zsh bash | cut -f1)" -- "$cur") )
}
_shai_bash_event_type() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' message tool_result error | cut -f1)" -- "$cur") )
}
_shai_bash_event_source() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' user assistant system tool | cut -f1)" -- "$cur") )
}
_shai_bash_tool_name() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [ -z "${_shai_dir:-}" ] || [ ! -d "${_shai_dir:-}" ]; then
    COMPREPLY=()
    return
  fi
  COMPREPLY=( $(compgen -W "$(for d in "${_shai_dir}/tools/"*/run.sh; do [ -x "$d" ] || continue; d="${d%/run.sh}"; n="${d##*/}"; p="$(jq -r '.description // empty' "$d/tool.json" 2>/dev/null)"; printf '%s\t%s\n' "$n" "$p"; done 2>/dev/null | cut -f1)" -- "$cur") )
}
_shai_bash_install_version() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [ -z "${_shai_dir:-}" ] || [ ! -d "${_shai_dir:-}" ]; then
    COMPREPLY=()
    return
  fi
  COMPREPLY=( $(compgen -W "$(if [ -L "${_shai_dir%/*}/current" ]; then for d in "${_shai_dir%/*}/"*/; do d="${d%/}"; n="${d##*/}"; [ "$n" = current ] || printf '%s\n' "$n"; done 2>/dev/null; fi | cut -f1)" -- "$cur") )
}
_shai_bash_policy_verb() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' list add remove test | cut -f1)" -- "$cur") )
}
_shai_bash_ci_verb() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' list add remove | cut -f1)" -- "$cur") )
}
_shai_bash_policy_action() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$(printf '%s\n' allow prompt deny | cut -f1)" -- "$cur") )
}

_shai_read() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--system --external" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_read shai-read
_shai_context() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--max-bytes" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_context shai-context
_shai_eval() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--tools-file" ]]; then
    local IFS=$'\n'
    COMPREPLY=( $(compgen -f -- "$cur") )
    compopt -o filenames 2>/dev/null
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--tools-file --model --max-tokens --dry-run --health-check" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_eval shai-eval
_shai_events() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--type" ]]; then
    _shai_bash_event_type
    return
  fi
  if [[ "$prev" == "--source" ]]; then
    _shai_bash_event_source
    return
  fi
  if [[ "$prev" == "--tool" ]]; then
    _shai_bash_tool_name
    return
  fi
  if [[ "$prev" == "--session" ]]; then
    _shai_bash_session_id
    return
  fi
  if [[ "$prev" == "--run" ]]; then
    _shai_bash_run_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--type --source --tool --session --run --after --before --recent --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_events shai-events
_shai_dispatch() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_dispatch shai-dispatch
_shai_loop() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--tools-file" ]]; then
    local IFS=$'\n'
    COMPREPLY=( $(compgen -f -- "$cur") )
    compopt -o filenames 2>/dev/null
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--tools --tools-file --model --max-tokens --quiet -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_loop shai-loop
_shai_print() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--debug --dispatches" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_print shai-print
_shai_stamp() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_stamp shai-stamp
_shai_ask() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--quiet --no-tools --model --max-tokens --external -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_ask shai-ask
_shai_repl() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--quiet -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_repl shai-repl
_shai_retry() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--run" ]]; then
    _shai_bash_run_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--quiet --run -q" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_retry shai-retry
_shai_sessions() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--recent --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_sessions shai-sessions
_shai_runs() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--session" ]]; then
    _shai_bash_session_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--session --recent --failed --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_runs shai-runs
_shai_trace() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--request --response --verbose --json" -- "$cur") )
    return
  fi
  local _shai_pos=0 _shai_val=0 _shai_i
  for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
    case "${COMP_WORDS[_shai_i]}" in
      --request)
        if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
          _shai_val=1
        fi
        _shai_i=$((_shai_i + 1))
        ;;
      --request=*) : ;;
      --response)
        if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
          _shai_val=1
        fi
        _shai_i=$((_shai_i + 1))
        ;;
      --response=*) : ;;
      -*) : ;;
      *)
        _shai_pos=$((_shai_pos + 1))
        ;;
    esac
  done
  if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 0 ]; then
    _shai_bash_run_id
    return
  fi
  COMPREPLY=()
}
complete -F _shai_trace shai-trace
_shai_stats() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--session" ]]; then
    _shai_bash_session_id
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--session --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_stats shai-stats
_shai_failures() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "list show summary" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    list)
      if [[ "$prev" == "--workflow" ]]; then
        _shai_bash_workflow_name
        return
      fi
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--workflow --category --after --before --recent --json" -- "$cur") )
        return
      fi
      COMPREPLY=()
      ;;
    show)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--json" -- "$cur") )
        return
      fi
      COMPREPLY=()
      ;;
    summary)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--after --before --json" -- "$cur") )
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_failures shai-failures
_shai_ledgers() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--workflow" ]]; then
    _shai_bash_workflow_name
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--workflow --recent --after --before --json" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_ledgers shai-ledgers
_shai_doctor() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_doctor shai-doctor
_shai_update() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--rollback" ]]; then
    _shai_bash_install_version
    return
  fi
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--check --list --rollback --version --prune --keep --dry-run --yes -y" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_update shai-update
_shai_version() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
}
complete -F _shai_version shai-version
_shai_tools() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  local _shai_pos=0 _shai_val=0 _shai_i
  for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
    case "${COMP_WORDS[_shai_i]}" in
      -*) : ;;
      *)
        _shai_pos=$((_shai_pos + 1))
        ;;
    esac
  done
  if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 0 ]; then
    local IFS=$'\n'
    COMPREPLY=( $(compgen -f -- "$cur") )
    compopt -o filenames 2>/dev/null
    return
  fi
  COMPREPLY=()
}
complete -F _shai_tools shai-tools
_shai_prompt() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  local _shai_pos=0 _shai_val=0 _shai_i
  for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
    case "${COMP_WORDS[_shai_i]}" in
      -*) : ;;
      *)
        _shai_pos=$((_shai_pos + 1))
        ;;
    esac
  done
  if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 0 ]; then
    _shai_bash_prompt_name
    return
  fi
  COMPREPLY=()
}
complete -F _shai_prompt shai-prompt
_shai_workflow() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "list run describe" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    list)
      COMPREPLY=()
      ;;
    run)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    describe)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_workflow shai-workflow
_shai_supervise() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "install uninstall start stop status repoint logs" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    install)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--interval" -- "$cur") )
        return
      fi
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          --interval)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --interval=*) : ;;
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    uninstall)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    start)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    stop)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    status)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--json" -- "$cur") )
        return
      fi
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    repoint)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--all --dry-run" -- "$cur") )
        return
      fi
      local _shai_nopos=0 _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          --all)
            _shai_nopos=1
            ;;
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_nopos" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    logs)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_workflow_name
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_supervise shai-supervise
_shai_prune() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--sessions --runs --ledgers --failures --dry-run --before" -- "$cur") )
    return
  fi
  COMPREPLY=()
}
complete -F _shai_prune shai-prune
_shai_completions() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "check generate install" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    check)
      COMPREPLY=()
      ;;
    generate)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_shell
        return
      fi
      COMPREPLY=()
      ;;
    install)
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_shell
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_completions shai-completions
_shai_config() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "policy ci" -- "$cur") )
    return
  fi
  case "${COMP_WORDS[1]}" in
    policy)
      if [[ "$prev" == "--tool" ]]; then
        _shai_bash_tool_name
        return
      fi
      if [[ "$prev" == "--action" ]]; then
        _shai_bash_policy_action
        return
      fi
      if [[ "$prev" == "--overlay" ]]; then
        local IFS=$'\n'
        COMPREPLY=( $(compgen -f -- "$cur") )
        compopt -o filenames 2>/dev/null
        return
      fi
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--tool --action --args --before --force --input --overlay --json" -- "$cur") )
        return
      fi
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          --tool)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --tool=*) : ;;
          --action)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --action=*) : ;;
          --args)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --args=*) : ;;
          --before)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --before=*) : ;;
          --input)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --input=*) : ;;
          --overlay)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --overlay=*) : ;;
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_policy_verb
        return
      fi
      COMPREPLY=()
      ;;
    ci)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--json --repo --name --command --timeout --env" -- "$cur") )
        return
      fi
      local _shai_pos=0 _shai_val=0 _shai_i
      for (( _shai_i = 1; _shai_i < COMP_CWORD; _shai_i++ )); do
        case "${COMP_WORDS[_shai_i]}" in
          --repo)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --repo=*) : ;;
          --name)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --name=*) : ;;
          --command)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --command=*) : ;;
          --timeout)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --timeout=*) : ;;
          --env)
            if [ $((_shai_i + 1)) -ge "$COMP_CWORD" ]; then
              _shai_val=1
            fi
            _shai_i=$((_shai_i + 1))
            ;;
          --env=*) : ;;
          -*) : ;;
          *)
            _shai_pos=$((_shai_pos + 1))
            ;;
        esac
      done
      if [ "$_shai_val" -eq 0 ] && [ "$_shai_pos" -eq 1 ]; then
        _shai_bash_ci_verb
        return
      fi
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}
complete -F _shai_config shai-config
